// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcNqzmxHft5p4CRGxFezZ5QEg4fLq8BA',
    appId: '1:20535554383:web:5ec2d8db42c91d5915953a',
    messagingSenderId: '20535554383',
    projectId: 'quotes-f51d2',
    authDomain: 'quotes-f51d2.firebaseapp.com',
    storageBucket: 'quotes-f51d2.appspot.com',
    measurementId: 'G-R7HG0EBB58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrp4aFnFQ2p0BDmzpwQI3gbkxlW1Jtz0',
    appId: '1:20535554383:android:95d15c69e968015215953a',
    messagingSenderId: '20535554383',
    projectId: 'quotes-f51d2',
    storageBucket: 'quotes-f51d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaCjFs80_SmdLSRddxeak5t5TozUTQ9yU',
    appId: '1:20535554383:ios:697e9963586ba00e15953a',
    messagingSenderId: '20535554383',
    projectId: 'quotes-f51d2',
    storageBucket: 'quotes-f51d2.appspot.com',
    iosBundleId: 'com.example.quotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaCjFs80_SmdLSRddxeak5t5TozUTQ9yU',
    appId: '1:20535554383:ios:697e9963586ba00e15953a',
    messagingSenderId: '20535554383',
    projectId: 'quotes-f51d2',
    storageBucket: 'quotes-f51d2.appspot.com',
    iosBundleId: 'com.example.quotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZcNqzmxHft5p4CRGxFezZ5QEg4fLq8BA',
    appId: '1:20535554383:web:02f3691a4bbc72fc15953a',
    messagingSenderId: '20535554383',
    projectId: 'quotes-f51d2',
    authDomain: 'quotes-f51d2.firebaseapp.com',
    storageBucket: 'quotes-f51d2.appspot.com',
    measurementId: 'G-LKKLRCQ6X0',
  );
}
